name: CI
on: [push, pull_request]
jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }

      # EITHER use the wrapper:
      # - name: Build & Test
      #   shell: pwsh
      #   run: ./gradlew.bat clean test --stacktrace --info

      # OR install a specific Gradle (no wrapper needed):
      - name: Install Gradle 8.7
        shell: pwsh
        run: |
          choco install gradle --version=8.7 -y
          gradle --version
      - name: Build & Test (global Gradle)
        shell: pwsh
        run: gradle clean test --stacktrace --info

      - name: Upload test report (HTML)
        if: always() && ${{ hashFiles('build/reports/tests/test/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test/
