name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Show repo root (debug)
        shell: pwsh
        run: |
          Get-Location
          dir -Force
          if (-not (Test-Path ./gradlew.bat)) { throw "gradlew.bat missing in repo root" }

      - name: Build & Test
        shell: pwsh
        run: ./gradlew.bat clean test --stacktrace --info

      - name: Upload test report (HTML)
        if: always() && ${{ hashFiles('build/reports/tests/test/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test/

      - name: Upload raw XML (fallback)
        if: always() && ${{ hashFiles('build/test-results/test/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-xml
          path: build/test-results/test/
