name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: .   # repo root

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Check Gradle version (should be 9.0)
        run: |
          $v = gradle --version
          $v
          if ($v -notmatch 'Gradle 9\.0') { throw "Runner Gradle is not 9.0" }

      - name: Build & Test
        run: gradle clean test --stacktrace --info

      - name: Upload test report (HTML)
        if: ${{ always() && hashFiles('build/reports/tests/test/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test/

      - name: Upload raw XML (fallback)
        if: ${{ always() && hashFiles('build/test-results/test/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-xml
          path: build/test-results/test/
