name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: app    # <-- change to your subfolder name

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Verify wrapper exists (fail fast)
        shell: pwsh
        run: |
          if (-not (Test-Path ./gradlew.bat)) { Write-Error "gradlew.bat missing in working directory"; exit 1 }
          if (-not (Test-Path ./gradle/wrapper/gradle-wrapper.jar)) { Write-Error "gradle-wrapper.jar missing"; exit 1 }

      - name: Build & Test
        shell: pwsh
        run: |
          ./gradlew.bat --version
          ./gradlew.bat clean test --stacktrace --info

      - name: Upload test report (HTML)
        if: always() && ${{ hashFiles('build/reports/tests/test/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test/
