name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: calculator   # <-- change to your real folder name

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Verify wrapper
        shell: pwsh
        run: |
          if (-not (Test-Path ./gradlew.bat)) { throw "gradlew.bat missing" }
          if (-not (Test-Path ./gradle/wrapper/gradle-wrapper.jar)) { throw "gradle-wrapper.jar missing" }
      - name: Build & Test
        shell: pwsh
        run: |
          ./gradlew.bat clean test --stacktrace --info
      - name: Upload test report
        if: always() && ${{ hashFiles('build/reports/tests/test/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test/
