name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: windows-latest
    env:
      PROJECT_DIR: .   # change to your subfolder if not at repo root
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17' }

      - name: Install Gradle 8.7 globally
        shell: pwsh
        run: |
          choco install gradle --version=8.7 -y
          gradle --version

      - name: Build & Test
        shell: pwsh
        working-directory: ${{ env.PROJECT_DIR }}
        run: gradle clean test --stacktrace --info

      - name: Upload test report (HTML)
        if: always() && ${{ hashFiles(format('{0}/build/reports/tests/test/**', env.PROJECT_DIR)) != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ${{ env.PROJECT_DIR }}/build/reports/tests/test/
