name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Gradle (fallback)
        shell: pwsh
        run: choco install gradle -y

      - name: Build & Test with global Gradle
        shell: pwsh
        run: |
          gradle --version
          gradle clean test --stacktrace --info

      - name: Upload test report (HTML)
        if: always() && ${{ hashFiles('build/reports/tests/test/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test/

      - name: Upload raw XML (fallback)
        if: always() && ${{ hashFiles('build/test-results/test/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-xml
          path: build/test-results/test/
