name: CI

on:
  push: 
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      # On Windows, prefer gradlew.bat (PowerShell shell by default)
      - name: Build & Test
        shell: pwsh
        run: |
          .\gradlew --version
          .\gradlew clean test --stacktrace --info

      - name: Upload test report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test/
      - name: Show reports tree (debug)
      if: always()
      shell: pwsh
      run: |
        Get-ChildItem -Recurse -Depth 3 build\reports | Format-List FullName
        Get-ChildItem -Recurse -Depth 3 build\test-results | Format-List FullName

