name: CI
on: [push, pull_request]

jobs:
  build-test:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
        working-directory: .   # set to your project folder if not root

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Check Gradle version (non-fatal)
        run: |
          $v = gradle --version | Out-String
          $ok = $v -match 'Gradle 9\.0(\.0)?'
          if (-not $ok) { Write-Warning "Expected Gradle 9.0.x, got:`n$v" } else { Write-Host $v }

      - name: Build & Test
        run: gradle clean test --stacktrace --info

      - name: Upload test report (HTML)
        if: ${{ always() && hashFiles('build/reports/tests/test/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test/

      - name: Upload raw XML (fallback)
        if: ${{ always() && hashFiles('build/test-results/test/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: test-results-xml
          path: build/test-results/test/
